# Generated by Django 6.0.5 on 2026-05-27 20:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('keyword', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('sink', 'Sink'), ('source', 'Source'), ('both', 'Both')], default='sink', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='scanner.project')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('output_dir', models.CharField(blank=True, default='', max_length=512)),
                ('error_message', models.TextField(blank=True, default='')),
                ('task_id', models.CharField(blank=True, default='', max_length=255)),
                ('subdomain_count', models.IntegerField(default=0)),
                ('resolved_count', models.IntegerField(default=0)),
                ('live_count', models.IntegerField(default=0)),
                ('port_count', models.IntegerField(default=0)),
                ('nuclei_finding_count', models.IntegerField(default=0)),
                ('secret_count', models.IntegerField(default=0)),
                ('api_endpoint_count', models.IntegerField(default=0)),
                ('takeover_count', models.IntegerField(default=0)),
                ('s3_bucket_count', models.IntegerField(default=0)),
                ('xss_finding_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='scanner.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('project', 'scan_date')},
            },
        ),
        migrations.CreateModel(
            name='S3Bucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket_name', models.CharField(max_length=512)),
                ('is_open', models.BooleanField(default=False)),
                ('contents', models.TextField(blank=True, default='')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s3_buckets', to='scanner.scan')),
            ],
            options={
                'ordering': ['bucket_name'],
            },
        ),
        migrations.CreateModel(
            name='NucleiFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.CharField(max_length=512)),
                ('name', models.CharField(max_length=512)),
                ('severity', models.CharField(max_length=50)),
                ('matched_at', models.CharField(max_length=2048)),
                ('extracted_results', models.TextField(blank=True, default='')),
                ('curl_command', models.TextField(blank=True, default='')),
                ('host', models.CharField(blank=True, default='', max_length=512)),
                ('ip', models.CharField(blank=True, default='', max_length=45)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nuclei_findings', to='scanner.scan')),
            ],
            options={
                'ordering': ['severity', 'template_id'],
            },
        ),
        migrations.CreateModel(
            name='DiffResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=50)),
                ('added', models.JSONField(default=list)),
                ('removed', models.JSONField(default=list)),
                ('changed', models.JSONField(default=list)),
                ('summary', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diffs_a', to='scanner.scan')),
                ('scan_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diffs_b', to='scanner.scan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APIEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdomain', models.CharField(blank=True, default='', max_length=512)),
                ('url', models.TextField()),
                ('source', models.CharField(blank=True, default='', max_length=255)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_endpoints', to='scanner.scan')),
            ],
            options={
                'ordering': ['subdomain', 'url'],
            },
        ),
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detector_name', models.CharField(max_length=512)),
                ('verified', models.BooleanField(default=False)),
                ('raw', models.TextField(blank=True, default='')),
                ('raw_v2', models.TextField(blank=True, default='')),
                ('file_path', models.CharField(blank=True, default='', max_length=1024)),
                ('source_metadata', models.JSONField(blank=True, default=dict)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secrets', to='scanner.scan')),
            ],
            options={
                'ordering': ['-verified', 'detector_name'],
            },
        ),
        migrations.CreateModel(
            name='Subdomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('ip', models.CharField(blank=True, default='', max_length=45)),
                ('record_type', models.CharField(blank=True, default='A', max_length=10)),
                ('resolved', models.BooleanField(default=False)),
                ('http_url', models.CharField(blank=True, default='', max_length=1024)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('http_title', models.CharField(blank=True, default='', max_length=1024)),
                ('technologies', models.JSONField(blank=True, default=list)),
                ('sources', models.JSONField(blank=True, default=list)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdomains', to='scanner.scan')),
            ],
            options={
                'ordering': ['-resolved', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_number', models.IntegerField()),
                ('protocol', models.CharField(blank=True, default='tcp', max_length=10)),
                ('service', models.CharField(blank=True, default='', max_length=255)),
                ('subdomain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='scanner.subdomain')),
            ],
            options={
                'ordering': ['port_number'],
            },
        ),
        migrations.CreateModel(
            name='Takeover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdomain_name', models.CharField(max_length=512)),
                ('vulnerable', models.BooleanField(default=False)),
                ('service', models.CharField(blank=True, default='', max_length=255)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='takeovers', to='scanner.scan')),
            ],
            options={
                'ordering': ['-vulnerable', 'subdomain_name'],
            },
        ),
        migrations.CreateModel(
            name='XSSFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('poc', models.TextField(blank=True, default='')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xss_findings', to='scanner.scan')),
            ],
        ),
        migrations.CreateModel(
            name='Dork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdomain_name', models.CharField(max_length=512)),
                ('dork_type', models.CharField(max_length=255)),
                ('query', models.TextField()),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dorks', to='scanner.scan')),
            ],
            options={
                'ordering': ['subdomain_name', 'dork_type'],
                'indexes': [models.Index(fields=['scan', 'subdomain_name'], name='scanner_dor_scan_id_df2502_idx')],
            },
        ),
        migrations.CreateModel(
            name='CrawledURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdomain', models.CharField(max_length=512)),
                ('url', models.TextField()),
                ('is_js', models.BooleanField(default=False)),
                ('is_api', models.BooleanField(default=False)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawled_urls', to='scanner.scan')),
            ],
            options={
                'ordering': ['subdomain', 'url'],
                'indexes': [models.Index(fields=['scan', 'subdomain'], name='scanner_cra_scan_id_e5d339_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='subdomain',
            index=models.Index(fields=['scan', 'name'], name='scanner_sub_scan_id_5eb41e_idx'),
        ),
        migrations.AddIndex(
            model_name='subdomain',
            index=models.Index(fields=['scan', 'resolved'], name='scanner_sub_scan_id_5e266a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='port',
            unique_together={('subdomain', 'port_number')},
        ),
    ]
