# Generated by Django 6.0.5 on 2026-05-27 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawledurl',
            name='local_path',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
