# Generated by Django 6.0.5 on 2026-05-28 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_crawledurl_local_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(default='info', max_length=50)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='scanner.scan')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ScanProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(default='idle', max_length=100)),
                ('step_index', models.IntegerField(default=0)),
                ('step_total', models.IntegerField(default=9)),
                ('message', models.CharField(blank=True, default='', max_length=512)),
                ('subs_found', models.IntegerField(default=0)),
                ('subs_resolved', models.IntegerField(default=0)),
                ('subs_live', models.IntegerField(default=0)),
                ('ports_found', models.IntegerField(default=0)),
                ('nuclei_found', models.IntegerField(default=0)),
                ('secrets_found', models.IntegerField(default=0)),
                ('endpoints_found', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='scanner.scan')),
            ],
        ),
    ]
