# Generated by Django 6.0.5 on 2026-05-30 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_scanlog_scanprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.CharField(blank=True, max_length=255, unique=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('asn_status', models.CharField(default='idle', max_length=20)),
                ('asn_cidr_count', models.IntegerField(default=0)),
                ('asn_ip_count', models.IntegerField(default=0)),
                ('asn_domain_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='scanner.organisation'),
        ),
        migrations.CreateModel(
            name='ASNCIDR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidr', models.CharField(max_length=64)),
                ('open_ips', models.JSONField(blank=True, default=list)),
                ('discovered_domains', models.JSONField(blank=True, default=list)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cidrs', to='scanner.organisation')),
            ],
            options={
                'ordering': ['cidr'],
                'unique_together': {('organisation', 'cidr')},
            },
        ),
    ]
