# Generated by Django 6.0.5 on 2026-06-01 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_organisation_project_organisation_asncidr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanlog',
            name='scan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='scanner.scan'),
        ),
    ]
